---
services:
  ollama:
    image: docker.io/ollama/ollama:latest
    container_name: ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    networks:
      - rag-network
    volumes:
      - ./ollama_data:/root/.ollama:Z,U
    devices:
      - nvidia.com/gpu=all
    restart: unless-stopped

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    depends_on:
      - ollama
      - searxng
    ports:
      - "3000:8080"
    networks:
      - rag-network
    volumes:
      - ./open-webui_data:/app/backend/data:Z,U
    environment:
      - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY}
      - ENABLE_OPENAI_API=${ENABLE_OPENAI_API}
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
      - ENABLE_RAG_WEB_SEARCH=True
      - RAG_WEB_SEARCH_ENGINE=searxng
      - SEARXNG_QUERY_URL=http://searxng:8080/search?q=<query>&engines=google
      - WEB_SEARCH_CONCURRENT_REQUESTS=${WEB_SEARCH_CONCURRENT_REQUESTS}
      - WEB_SEARCH_RESULT_COUNT=${WEB_SEARCH_RESULT_COUNT}
    restart: unless-stopped

  searxng:
    image: docker.io/searxng/searxng:latest
    container_name: searxng
    networks:
      - rag-network
    ports:
      - "8080:8080"
    volumes:
      - ./searxng_data:/etc/searxng:Z,U
    environment:
      - SEARXNG_LIMITER=false
      - BASE_URL=http://searxng:8080/
    restart: unless-stopped

networks:
  rag-network:
    driver: bridge
